### ISSUE TITLE
Connection service closed unexpectedly

### ISSUE THREAD

**Issue by eeahm** [SGprooo/TextualIRCBin#1]
Hi, first of all thank you for taking the time to compile this sw, I paid for the official version but I was testing it on a friend's computer and I couldn't make a connection work. We fully allowed it on the firewall, tried Rizon SSL 6697 and non-SSL 6667, tried to add a self signed cert and everything else, I've been using Textual on my Mac for years also so I know there is something going on here.

What do you think it could be?

**Comment by eeahm** [comment]
Fair enough but why is this build existing at all then?

**Comment by SGprooo** [comment]
> Fair enough but why is this build existing at all then?

I just thought if you can't get it to work, building it yourself would certainly solve the issue.
Because neither would I would choose to go through and try looking into specifics.

**Comment by eeahm** [comment]
Thanks man, I'm thinking it's something else with the certs or the system anyway, I will try on other Macs and we'll find a solution.
